openapi: 3.0.0
info:
  description: ""
  version: 1.0.0
  title: "Media Exchange System"
  contact:
    name: "Support"
    url: "https://github.com/gek64/mes/issues/new"
  license:
    name: "GNU General Public License v3.0"
    url: "https://github.com/gek64/mes/raw/main/LICENSE"
servers:
  - url: "http://localhost"
  - url: "http://127.0.0.1"
  - url: "http://[::1]"
tags:
  - name: "upload"
    description: "上传文件"
paths:
  /upload/raw/{fileName}:
    post:
      tags:
        - "upload"
      summary: "以 application/octet-stream 方式上传单个文件"
      description: ""
      operationId: "Raw"
      parameters:
        - name: fileName
          in: path
          allowEmptyValue: false
          required: true
          schema:
            type: string
      requestBody:
        $ref: "#/components/requestBodies/uploadRawData"
      responses:
        "200":
          description: "upload done"
components:
  requestBodies:
    uploadRawData:
      content:
        application/octet-stream:
          schema:
            type: string
            format: binary
      description: Raw
      required: true
  schemas:
    Test:
      type: object
      properties:
        id:
          type: integer
          format: int64
        status:
          type: string